### ISSUE TITLE
The GitHub link may be replaced by the GitHub Icon

### ISSUE THREAD

**Issue by Shivyoddha** [SauravMukherjee44/Aec-Library-Website#910]
### Feature description

The GitHub link(Under - Contact Us) to this page is in for of text which can be replaced by its icon, which will add to attractiveness of the site.

![image](https://user-images.githubusercontent.com/97729353/193459446-8ce68f59-0bf1-4afc-8e35-f6202d9962e0.png)

Hi @SauravMukherjee44  
Please assign me with this issue .

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/SauravMukherjee44/Aec-Library-Website/blob/main/CODE_OF_CONDUCT.md)

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by Abhisht18** [comment]
can you assign this to me

**Comment by RishitaGangwal** [comment]
![page](https://user-images.githubusercontent.com/88449534/193506078-3c644b35-0723-4794-b19f-de32f9828e62.jpeg)

Under Contact Section:
We can change link (LinkedIn, Github, Twitter, YouTube) written in text form to their icons it is a visual invitation to users to try out the latest and greatest features of any Web application. And due to this our website will look more attractive.

@SauravMukherjee44 Hey, please assign this an issue to me.

**Comment by RishitaGangwal** [comment]
On the home page, icons are not added for the same which I have mentioned above. Its written in text form.
