### ISSUE TITLE
Some Minor changes in the Donate Books Section

### ISSUE THREAD

**Issue by DhruvRathi2001** [SauravMukherjee44/Aec-Library-Website#924]
In the Donate Books Section, in Book Donation Form- 

The Address section  must be a "text box" instead of  a  single input line.
And also as a tradition Address are always mentioned in Text box to user for specifying Address more Accurately.

![book donation img](https://user-images.githubusercontent.com/94394117/193508454-a539e7cf-7079-419b-97ab-c4c67debc7dc.png)

@SauravMukherjee44  Can you please assign me this issue, I would love to contribute this for HACKTOBERFEST

**Comment by amisha123prajapati** [comment]
Hello,
Can you please assign this issue to me, I want to contribute to it!

**Comment by DhruvRathi2001** [comment]
> Hello, Can you please assign this issue to me, I want to contribute to it!

Hey @amisha123prajapati  please find some other issues as I have raised issue long back and waiting it to be assigned.

**Comment by SauravMukherjee44** [comment]
Go for it!

**Comment by cmaguluri1305** [comment]
I want to contribute can you assign the issue to me?

**Comment by amisha123prajapati** [comment]
Hello Maintainer!
@SauravMukherjee44 , I am beginner in Hacktoberfest and want to learn and contribute to it. I have solved this issue, you can see in the below screenshot. Please assign this issue to me so that I can create pull request.

Thanks!


![Screenshot (2193)](https://user-images.githubusercontent.com/86883460/193724612-19dbcf75-12d6-4279-8f3a-46e6e254893e.png)
